apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespaces.yaml
  - network-policy.yaml
  - trade-service.yaml
  - position-service.yaml
  - risk-service.yaml
  - alm-service.yaml
  - bo-service.yaml
  - market-data-service.yaml
  - web.yaml
