apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nexustreasury-staging
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: nexustreasury
    environment: staging
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/manassehkafoh/nexustreasury
    targetRevision: main
    path: infra/helm/nexustreasury
    helm:
      valueFiles:
        - values-staging.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: nexus-staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
    retry:
      limit: 3
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 3m
  revisionHistoryLimit: 5
